### ISSUE TITLE
Ability to load collection, and make "Lucky Dip" gallery from Wellcome endpoint

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-gallery#1]
...maybe as query string param

?collection=http://wellcome...

Or as a piece of UI (like a browser address bar at the top)

Special case:

http://wellcomelibrary.org/service/collections/lucky-dip/open/

This is a dynamic collection. We could deploy a version that talks to this that the user can keep refreshing to see 20 random images from Wellcome (warning - kinda NSFW). From script you might want to append a timestamp in case XHR is too keen on caching the response.

**Comment by tomcrane** [comment]
http://digirati-co-uk.github.io/iiif-gallery/src/?collection=http://wellcomelibrary.org/service/collections/genres/Advertising%20cards/

**Comment by stephenwf** [comment]
Once PR #7 is merged, the link you have put in above will work as expected

**Comment by stephenwf** [comment]
If you click the link you posted (http://digirati-co-uk.github.io/iiif-gallery/src/?collection=http://wellcomelibrary.org/service/collections/genres/Advertising%20cards/)

It now loads the collection
